export const TOGGLE_PANEL_CONST = 'TOGGLE_PANEL_CONST';
export const SET_TASK_DETAILS = 'SET_TASK_DETAILS';
export const SET_TASK_ADDRESS = 'SET_TASK_ADDRESS';
export const SET_ACTIVE_SERVICE_ITEM = 'SET_ACTIVE_SERVICE_ITEM';
export const SET_AVIABLE_TASK = 'SET_AVIABLE_TASK';
