export const ADD_TASK_TO_LIST = 'ADD_TASK_TO_LIST';
export const REMOVE_TASK_FROM_LIST = 'REMOVE_TASK_FROM_LIST';
export const SET_TASK_LIST = 'SET_TASK_LIST';
export const SET_EDIT_DETAILS = 'SET_EDIT_DETAILS';
