export const HEADER_TOGGLE = 'HEADER_TOGGLE';
export const PANEL_TOGGLE = 'PANEL_TOGGLE';
export const CONFIRM_MODAL_TOGGLE = 'CONFIRM_MODAL_TOGGLE';
export const EDIT_TOGGLE = 'EDIT_TOGGLE';
export const MAP_TOGGLE = 'MAP_TOGGLE';
